- id: autoflake8
  name: autoflake8
  entry: autoflake8
  language: python
  "types": [python]
  require_serial: true
  args:
    - "--in-place"
    - "--expand-star-imports"
    - "--remove-duplicate-keys"
    - "--remove-unused-variables"
