name: Fuzz
on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  fuzz:
    strategy:
      matrix:
        options:
          - ""
          - "--expand-star-imports"
          - "--remove-duplicate-keys"
          - "--remove-unused-variables"
          - "--remove-duplicate-keys --remove-unused-variables"
          - "--expand-star-imports --remove-duplicate-keys"
          - "--expand-star-imports --remove-duplicate-keys --remove-unused-variables"

    name: fuzz (${{ matrix.options }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.x

      - run: pip install poetry

      - run: poetry install

      - name: run fuzz
        run: ./scripts/fuzz.sh ${{ matrix.options }}
