name: Build
on:
  push:
    branches:
      main

  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
        os:
          - macos
          - ubuntu

    name: tests
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-python@v2.2.2

      - name: test deps
        run: pip install pytest

      - name: install deps
        run: pip install -e .

      - name: run tests
        run: pytest

