name: Publish
on: create

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        if: github.event.ref_type == 'tag'

      - uses: actions/setup-python@v2.2.2
        if: github.event.ref_type == 'tag'
        with:
          python-version: 3.x

      - run: pip install poetry
        if: github.event.ref_type == 'tag'

      - name: poetry cache
        if: github.event.ref_type == 'tag'
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pypoetry
          key: "${{ hashFiles('poetry.lock') }}"

      - run: poetry install --no-dev
        if: github.event.ref_type == 'tag'

      - run: poetry publish
        if: github.event.ref_type == 'tag'
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
